name: abc_rl
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=hda65f42_8
  - c-ares=1.34.6=hb03c661_0
  - ca-certificates=2025.12.2=h06a4308_0
  - certifi=2024.8.30=pyhd8ed1ab_0
  - cmake=4.2.1=hc85cc9f_0
  - keyutils=1.6.3=hb9d3cd8_0
  - krb5=1.21.3=h659f571_0
  - ld_impl_linux-64=2.45=default_hbd61a6d_104
  - libcurl=8.17.0=h4e3cde8_1
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=hd590300_2
  - libexpat=2.7.3=hecca717_0
  - libffi=3.4.6=h2dba641_1
  - libgcc=15.2.0=h69a1729_7
  - libgcc-ng=15.2.0=h166f726_7
  - libgomp=15.2.0=h4751f2c_7
  - liblzma=5.8.1=hb9d3cd8_2
  - liblzma-devel=5.8.1=hb9d3cd8_2
  - libnghttp2=1.67.0=had1ee68_0
  - libnsl=2.0.1=hb9d3cd8_1
  - libsqlite=3.51.1=h0c1763c_0
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libuv=1.51.0=hb03c661_1
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - ncurses=6.5=h7934f7d_0
  - openssl=3.6.0=h26f9b46_0
  - pip=22.3.1=py37h06a4308_0
  - pthread-stubs=0.3=h0ce48e5_1
  - pybind11=2.13.6=pyh1ec8472_2
  - pybind11-global=2.13.6=pyh415d2e4_2
  - python=3.7.12=hf930737_100_cpython
  - readline=8.3=h853b02a_0
  - rhash=1.4.6=hb9d3cd8_1
  - setuptools=65.6.3=py37h06a4308_0
  - sqlite=3.51.1=hbc0de68_0
  - tk=8.6.15=h54e0aa7_0
  - wheel=0.38.4=py37h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.8.1=hbcc6ac9_2
  - xz-gpl-tools=5.8.1=hbcc6ac9_2
  - xz-tools=5.8.1=hb9d3cd8_2
  - zlib=1.3.1=hb25bd0a_0
  - zstd=1.5.7=hb78ec9c_6
  - pip:
      - charset-normalizer==3.4.4
      - cloudpickle==2.2.1
      - cycler==0.11.0
      - dgl==1.1.3
      - farama-notifications==0.0.4
      - fonttools==4.38.0
      - gym==0.26.2
      - gym-notices==0.1.0
      - gymnasium==0.28.1
      - idna==3.10
      - importlib-metadata==6.7.0
      - jax-jumpy==1.0.0
      - kiwisolver==1.4.5
      - matplotlib==3.5.3
      - networkx==2.6.3
      - numpy==1.21.6
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cudnn-cu11==8.5.0.96
      - packaging==24.0
      - pandas==1.3.5
      - pillow==9.5.0
      - psutil==7.1.3
      - pyparsing==3.1.4
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - requests==2.31.0
      - scipy==1.7.3
      - six==1.17.0
      - stable-baselines3==2.0.0
      - torch==1.13.0
      - tqdm==4.67.1
      - typing-extensions==4.7.1
      - urllib3==2.0.7
      - zipp==3.15.0
